In [10]:
import numpy as np

In [11]:
Elist = [[5,3,0],
        [3,4,-1],
        [0,-1,2]]
E = np.array(Elist)/10000

In [16]:
N = np.array([[2,2,1]])/3
Nleft = N
Nright = N.T

In [17]:
out = np.dot(Nleft, E)

In [18]:
out2 = np.dot(out, Nright)

In [19]:
out2

array([[0.00064444]])

In [22]:
Pdot = np.dot(E, Nright)
Pdot_value = np.sqrt((Pdot[1]**2 + Pdot[2]**2 + Pdot[0]**2))
Pdot_value

array([0.00068718])

In [24]:
cos_alpha = out2 / Pdot_value

In [25]:
alpha = np.arccos(cos_alpha)

In [28]:
alpha*180/np.pi

array([[20.31395337]])

In [43]:
p2 = np.array([[3,0,-6]])/np.sqrt(45)
p2r = p2.T
p2l = p2

In [44]:
elongation1 = np.dot(p2l, E)
elongation = np.dot(elongation1, p2r)

In [45]:
elongation

array([[0.00026]])

In [46]:
Pdot = np.dot(E, p2r)
print(Pdot)
Pdot_value = np.sqrt((Pdot[1]**2 + Pdot[2]**2 + Pdot[0]**2))
Pdot_value

[[ 0.00022361]
 [ 0.00022361]
 [-0.00017889]]


array([0.00036332])

In [47]:
cos_alpha2 = elongation/Pdot_value
alpha2 = np.arccos(cos_alpha2) *180/np.pi

In [48]:
alpha2

array([[44.30543766]])