In [1]:
import numpy as np
from scipy.io import loadmat
import matplotlib.pyplot as plt
import utide

In [2]:
m1 = loadmat("./Data/1/t1")

In [19]:
m1["t1"]

array([[    900,    1800,    2700, ..., 5355000, 5355900, 5356800]],
      dtype=int32)

In [4]:
m1

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri May 13 17:44:15 2016',
 '__version__': '1.0',
 '__globals__': [],
 't1': array([[    900,    1800,    2700, ..., 5355000, 5355900, 5356800]],
       dtype=int32)}

In [5]:
v1 = loadmat("./Data/1/v1")

In [6]:
v1

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri May 13 17:44:15 2016',
 '__version__': '1.0',
 '__globals__': [],
 'v1': array([[ 3.0385111e-14-2.3689434e-15j,  5.2217337e-14-4.6933824e-15j,
          3.3002539e-11-2.5679178e-11j, ...,
          3.4714399e-01+3.5771832e-02j,  5.0936630e-02+8.6331846e-03j,
         -2.6901432e-01-4.7730377e-02j]])}

In [14]:
v1['v1'].shape

(1, 5952)

In [22]:
5760

5760

In [23]:
m2 = loadmat("./Data/1/t2")

In [29]:
m2['t2'][0,192:]

array([ 173700,  174600,  175500, ..., 5355000, 5355900, 5356800],
      dtype=int32)

In [25]:
def read_data(base_path):
    name = ["t1", "t2", "t3", "t4", "v1", "v2", "v3", "v4"]
    data = []
    for i in name:
        path = base_path + i + ".mat"
        tmp = loadmat(path)
        tmp_data = tmp[i]
        
        data.append(tmp_data.reshape(-1))
    
    return data

In [26]:
data = read_data("./Data/1/")

In [27]:
bunch1_1 = utide.solve(data[0], data[4], lat=30)

solve: matrix prep ... solution ... diagnostics ... done.


In [28]:
tide = utide.reconstruct(data[0], bunch1_1)

prep/calcs ... done.


In [29]:
tide

{'t_in': array([    900,    1800,    2700, ..., 5355000, 5355900, 5356800],
       dtype=int32),
 'epoch': 'python',
 'constit': None,
 'min_SNR': 2,
 'min_PE': 0,
 't_mpl': array([    900,    1800,    2700, ..., 5355000, 5355900, 5356800],
       dtype=int32),
 'h': array([633.86066412, 633.86067445, 633.86068478, ..., 633.92212208,
        633.92213241, 633.92214274])}

In [57]:
comb_t = loadmat("./Sampling/combn_hour.mat")

In [58]:
comb_t['combn']

array([[13, 13],
       [14, 10],
       [ 2,  9],
       ...,
       [ 6,  8],
       [15,  5],
       [ 1, 10]], dtype=uint8)

In [59]:
comb_t['combn'].shape

(2184, 2)

In [30]:
constitue = loadmat("./UTide/ut_constants.mat")

In [32]:
constitue.keys()

dict_keys(['__header__', '__version__', '__globals__', 'const', 'sat', 'shallow', 'ut_version'])

In [46]:
constitue["const"][0][0][0]

array(['Z0  ', 'SA  ', 'SSA ', 'MSM ', 'MM  ', 'MSF ', 'MF  ', 'ALP1',
       '2Q1 ', 'SIG1', 'Q1  ', 'RHO1', 'O1  ', 'TAU1', 'BET1', 'NO1 ',
       'CHI1', 'PI1 ', 'P1  ', 'S1  ', 'K1  ', 'PSI1', 'PHI1', 'THE1',
       'J1  ', '2PO1', 'SO1 ', 'OO1 ', 'UPS1', 'ST36', '2NS2', 'ST37',
       'ST1 ', 'OQ2 ', 'EPS2', 'ST2 ', 'ST3 ', 'O2  ', '2N2 ', 'MU2 ',
       'SNK2', 'N2  ', 'NU2 ', 'ST4 ', 'OP2 ', 'GAM2', 'H1  ', 'M2  ',
       'H2  ', 'MKS2', 'ST5 ', 'ST6 ', 'LDA2', 'L2  ', '2SK2', 'T2  ',
       'S2  ', 'R2  ', 'K2  ', 'MSN2', 'ETA2', 'ST7 ', '2SM2', 'ST38',
       'SKM2', '2SN2', 'NO3 ', 'MO3 ', 'M3  ', 'NK3 ', 'SO3 ', 'MK3 ',
       'SP3 ', 'SK3 ', 'ST8 ', 'N4  ', '3MS4', 'ST39', 'MN4 ', 'ST9 ',
       'ST40', 'M4  ', 'ST10', 'SN4 ', 'KN4 ', 'MS4 ', 'MK4 ', 'SL4 ',
       'S4  ', 'SK4 ', 'MNO5', '2MO5', '3MP5', 'MNK5', '2MP5', '2MK5',
       'MSK5', '3KM5', '2SK5', 'ST11', '2NM6', 'ST12', '2MN6', 'ST13',
       'ST41', 'M6  ', 'MSN6', 'MKN6', 'ST42', '2MS6', '2MK6', 'NSK6',
      

In [54]:
len(constitue["const"][0][0])

13