In [17]:
import pytest

!python -m pytest --doctest-modules test_automata.py

============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/xiexun/OneDrive - Imperial College London/ACSE/ACSE-1/lectures/Assighment
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.3.0, remotedata-0.3.1
collected 4 items                                                              

test_automata.py ....                                                    [100%]

=========================== 4 passed in 5.05 seconds ===========================


In [18]:
import numpy
import automata
# Generate random initial state.
X = numpy.random.random((16, 16))>0.3 # call module.
Z = automata.lifetri(X, 10)
print(X.astype(int))
print(Z.astype(int))

[[0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1]
 [0 1 0 1 1 1 0 1 1 0 1 0 1 0 1 1]
 [1 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1]
 [1 1 1 1 1 1 1 0 0 1 0 1 1 0 1 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0]
 [1 0 0 1 1 1 0 1 1 0 1 1 0 1 1 1]
 [1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0]
 [1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0]
 [1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1]
 [0 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1]
 [1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 0]
 [1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1]
 [0 1 1 1 0 0 1 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 1 1 1 0 1 0 1 1 0 1 1 1]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0

In [19]:
import pylint
!pylint automata.py

************* Module automata
automata.py:99:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
automata.py:48:0: R0912: Too many branches (22/12) (too-many-branches)
automata.py:136:0: R0914: Too many local variables (20/15) (too-many-locals)
automata.py:154:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
automata.py:200:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
automata.py:200:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
automata.py:136:0: R0912: Too many branches (28/12) (too-many-branches)
automata.py:136:0: R0915: Too many statements (52/50) (too-many-statements)

------------------------------------------------------------------
Your code has been rated at 9.53/10 (previous run: 9.53/10, +0.00)



In [20]:
!pylint test_automata.py


--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

