In [3]:
import pytest

!python -m pytest --doctest-modules test_automata.py 

============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/xiexun/OneDrive - Imperial College London/ACSE/ACSE-1/lectures/Assighment
plugins: openfiles-0.3.2, arraydiff-0.3, doctestplus-0.3.0, remotedata-0.3.1
collected 4 items                                                              

test_automata.py ...F                                                    [100%]

=================================== FAILURES ===================================
_________________________________ test_lifegen _________________________________

    def test_lifegen():
        '''
        function for test for game of life in generic condition
        '''
        # example from life Figure 3
        lis = [0 for i in range(25)]
        lis[11] = lis[12] = lis[13] = 1
        init = np.array(lis)
    
        lis2 = [0 for i in range(25)]
        lis2[7] = lis2[12] = lis2[17] = 1
        final = 

In [3]:
import numpy
import automata
# Generate random initial state.
X = numpy.random.randint(0, 6, (16, 16)) # call module.
print(X[1:-1,1:-1])
print(X.max())
Z = automata.sandpile(X)

[[2 2 1 3 1 2 3 2 1 0 5 3 3 2]
 [5 2 0 1 2 5 0 4 1 0 3 3 2 0]
 [2 5 2 2 1 2 5 4 2 5 4 3 4 0]
 [1 0 3 1 4 1 1 0 5 0 0 1 3 1]
 [5 0 4 0 2 1 1 3 3 3 4 3 5 5]
 [5 5 3 4 4 1 4 4 1 4 2 3 3 2]
 [4 4 2 4 0 2 1 5 0 1 0 0 1 4]
 [5 2 2 4 0 0 2 1 2 2 3 2 1 1]
 [5 4 2 1 2 0 3 3 0 1 4 1 3 3]
 [2 4 4 4 0 2 5 0 0 3 3 5 0 2]
 [0 0 0 1 1 1 4 4 1 1 5 2 1 5]
 [0 0 2 1 5 1 2 4 1 1 2 2 1 1]
 [1 5 4 2 3 4 1 1 4 5 5 5 2 5]
 [2 2 3 5 3 2 2 3 4 1 3 2 0 5]]
5
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 4. 4. 4. 5. 5. 1. 1. 3. 2. 2. 3. 2. 4. 3. 0. 0.]
 [0. 5. 2. 2. 1. 3. 1. 2. 3. 2. 1. 0. 5. 3. 3. 2. 1. 0.]
 [0. 2. 5. 2. 0. 1. 2. 5. 0. 4. 1. 0. 3. 3. 2. 0. 4. 0.]
 [0. 5. 2. 5. 2. 2. 1. 2. 5. 4. 2. 5. 4. 3. 4. 0. 5. 0.]
 [0. 1. 1. 0. 3. 1. 4. 1. 1. 0. 5. 0. 0. 1. 3. 1. 5. 0.]
 [0. 4. 5. 0. 4. 0. 2. 1. 1. 3. 3. 3. 4. 3. 5. 5. 5. 0.]
 [0. 4. 5. 5. 3. 4. 4. 1. 4. 4. 1. 4. 2. 3. 3. 2. 5. 0.]
 [0. 5. 4. 4. 2. 4. 0. 2. 1. 5. 0. 1. 0. 0. 1. 4. 4. 0.]
 [0. 4. 5. 2. 2. 4. 0. 0. 2. 1. 2. 2. 3. 2. 1. 1. 

In [ ]:
import numpy as np
x = np.zeros((5,5))
x[2][1] = 1
x[2][2] = 1
x[2][3] = 1
print(x)

'''
print(x.sum())
sum = x.sum()
x = x.astype(int)
print(x)
if sum == 3:
  
    x[0,0] = 1
print(x)
'''

import automata
out = automata.life(x,1, False)
type(out)
print(out)

In [ ]:
for i in range(1):
    print('a')

In [ ]:
x

In [ ]:
x[0:3,1:4].sum() == 3

In [ ]:
x[1][2]=1

In [ ]:
x

In [21]:
import automata
import numpy as np
'''
init_mat = np.zeros((5,5))
init_mat[2,1:4] = 1

final_mat = np.zeros((5,5))
final_mat[1:4,2] = 1
print(init_mat)
print(final_mat)
init_mat = init_mat == 1
print(init_mat)
init_mat = init_mat.astype(int)
print(init_mat)
'''
init_mat2 = np.zeros((5,5))
init_mat2[1,1:4] = 1
init_mat2[2][3] = 1
init_mat2[3][2] = 1

final_mat2 = np.zeros((5,5))
final_mat2[0,2:] = 1
final_mat2[1][-1] = 1
final_mat2[2][-2] = 1
print(init_mat2)
print(final_mat2)
b = automata.life(init_mat2, 4, True)
print(b.astype(int))
print((b.astype(int) == final_mat2).all())
print(automata.life(init_mat2, 4, True))
'''
a = automata.life(init_mat, 1)
#final_mat = final_mat == 1
#print(a)
#print(final_mat)
#(a == final_mat).all()

b = automata.life(init_mat2, 4, True)
final_mat2 = final_mat2 == 1
print(b)
print(init_mat2)
print(final_mat2)
(b == final_mat2).all()
'''

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 1 1 1]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
True
[[False False  True  True  True]
 [False False False False  True]
 [False False False  True False]
 [False False False False False]
 [False False False False False]]


'\na = automata.life(init_mat, 1)\n#final_mat = final_mat == 1\n#print(a)\n#print(final_mat)\n#(a == final_mat).all()\n\nb = automata.life(init_mat2, 4, True)\nfinal_mat2 = final_mat2 == 1\nprint(b)\nprint(init_mat2)\nprint(final_mat2)\n(b == final_mat2).all()\n'

In [3]:
(a == final_mat).all()

True